import { useEffect, useMemo, useState } from "react";
import "./App.css";
import { Login, Signup } from "./pages.jsx";
import { createPatient, createReferral, downloadUrl, facilities, listPatients, login, me, patientScans, register, setToken, uploadScan } from "./api";
import fundImage from "./assets/fund.jpg";
const blank = { name: "", age: "", gender: "", diabetes: "" };
const risk = (v) => v ? `${v[0].toUpperCase()}${v.slice(1)} risk` : "Pending";
export default function App() {
 const [page,setPage]=useState("home"),[user,setUser]=useState(null),[patient,setPatient]=useState(blank),[image,setImage]=useState(null),[result,setResult]=useState(null),[patients,setPatients]=useState([]),[profile,setProfile]=useState(null),[history,setHistory]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[places,setPlaces]=useState([]),[place,setPlace]=useState("");
 const preview=useMemo(()=>image&&URL.createObjectURL(image),[image]); useEffect(()=>{me().then(setUser).catch(()=>setToken(null))},[]); useEffect(()=>()=>preview&&URL.revokeObjectURL(preview),[preview]);
 const screening=()=>{setPatient(blank);setImage(null);setResult(null);setError("");setPage("screening")};
 async function auth(v,signup){const account=signup?await register(v):await login(v.username,v.password);setUser(account);screening()}
 async function scan(){if(!patient.name||!image)return setError("Enter patient details and select a fundus image.");setBusy(true);setError("");try{const p=await createPatient({full_name:patient.name,age:Number(patient.age)||null,gender:patient.gender||null,diabetes_type:patient.diabetes||null});const s=await uploadScan(image,p.id,p.full_name);setResult({...s,patient:p});setPage("result")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function showHistory(){try{setPatients(await listPatients());setPage("history")}catch(e){setError(e.message)}} async function showProfile(p){try{setProfile(p);setHistory(await patientScans(p.id));setPage("profile")}catch(e){setError(e.message)}} async function referral(){try{setPlaces(await facilities());setPlace("");setPage("referral")}catch(e){setError(e.message)}} async function submitReferral(){const p=places.find(x=>x.id===place);if(!p)return setError("Choose a referral facility.");setBusy(true);try{const r=await createReferral(result.scan_id,{facility_name:p.name,facility_contact:p.contact});window.open(downloadUrl(`/referrals/${r.id}/letter`),"_blank","noopener");setPage("result")}catch(e){setError(e.message)}finally{setBusy(false)}}
 const nav=<nav className="screening-nav"><button className="screening-logo" onClick={()=>setPage("home")}>RETO</button>{user&&<div className="app-nav"><button onClick={screening}>New screening</button><button onClick={showHistory}>Patient history</button><button onClick={()=>{setToken(null);setUser(null);setPage("home")}}>Log out</button></div>}</nav>;
 if(page==="login")return <Login goHome={()=>setPage("home")} switchMode={()=>setPage("signup")} onSuccess={v=>auth(v,false)}/>; if(page==="signup")return <Signup goHome={()=>setPage("home")} switchMode={()=>setPage("login")} onSuccess={v=>auth(v,true)}/>;
 if(page==="history")return <Shell nav={nav}><p className="screening-eyebrow">PATIENT HISTORY</p><h1>Recent patients.</h1><div className="patient-list">{patients.map(p=><button key={p.id} className="patient-row" onClick={()=>showProfile(p)}><span><b>{p.full_name}</b><small>{p.age||"—"} years · {p.gender||"Not recorded"}</small></span><span>View profile →</span></button>)}{!patients.length&&<p>No patients have been recorded yet.</p>}</div></Shell>;
 if(page==="profile")return <Shell nav={nav}><button className="back-step" onClick={showHistory}>← Patient history</button><p className="screening-eyebrow">PATIENT PROFILE</p><h1>{profile?.full_name}</h1><p>{profile?.age||"—"} years · {profile?.gender||"Not recorded"} · Diabetes: {profile?.diabetes_type||"Not recorded"}</p><h2>Past scans</h2><div className="patient-list">{history.map(s=><div className="patient-row" key={s.scan_id}><span><b>{risk(s.risk_level)}</b><small>{new Date(s.created_at).toLocaleString()}</small></span><a href={downloadUrl(`/scans/${s.scan_id}/report`)} target="_blank" rel="noreferrer">Download report</a></div>)}{!history.length&&<p>No previous scans for this patient.</p>}</div></Shell>;
 if(page==="referral")return <Shell nav={nav}><button className="back-step" onClick={()=>setPage("result")}>← Result</button><p className="screening-eyebrow">REFERRAL</p><h1>Choose a facility.</h1><select className="facility-select" value={place} onChange={e=>setPlace(e.target.value)}><option value="">Select facility</option>{places.map(p=><option key={p.id} value={p.id}>{p.name} — {p.city}</option>)}</select>{error&&<p className="form-error">{error}</p>}<button className="continue-btn" onClick={submitReferral} disabled={busy}>{busy?"Creating…":"Create referral and download letter →"}</button></Shell>;
 if(page==="result")return <main className="screening-page"><div className="screening-wrapper">{nav}<section className="result-page"><p className="screening-eyebrow">SCREENING RESULT</p><h1>Screening summary.</h1><div className="result-card"><div className="result-top-grid"><div><p className="result-label">RISK LEVEL</p><h2>{risk(result?.risk_level)}</h2><p className="result-description">Diabetic retinopathy probability: {Math.round((result?.prediction?.diabetic_retinopathy?.probability||0)*100)}%</p></div><div className="confidence-box"><p>MODEL VERSION</p><strong>{result?.model_version}</strong></div></div><div className="result-image-section"><img src={downloadUrl(result?.heatmap_url)} alt="Coloured Grad-CAM heatmap"/></div><p className="result-note">Only the coloured Grad-CAM explanation is shown. This screening result does not replace clinical diagnosis.</p><div className="result-actions"><a className="secondary-action" href={downloadUrl(`/scans/${result?.scan_id}/report`)} target="_blank" rel="noreferrer">Download PDF report</a><button className="secondary-action" onClick={referral}>Create referral</button><button className="new-screening-btn" onClick={screening}>Start another screening →</button></div></div></section></div></main>;
 if(page==="screening")return <main className="screening-page"><div className="screening-wrapper">{nav}<section className="screening-content"><div className="step-panel"><div className="screening-heading"><p className="screening-eyebrow">NEW SCREENING</p><h1>Patient and image.</h1><p className="screening-intro">Enter patient details, then upload a retinal fundus image for analysis.</p></div><div className="screening-form"><Field label="Patient name"><input value={patient.name} onChange={e=>setPatient({...patient,name:e.target.value})}/></Field><div className="form-row"><Field label="Age"><input type="number" min="1" max="120" value={patient.age} onChange={e=>setPatient({...patient,age:e.target.value})}/></Field><Field label="Gender"><select value={patient.gender} onChange={e=>setPatient({...patient,gender:e.target.value})}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></Field></div><Field label="Diabetes type / history"><input value={patient.diabetes} onChange={e=>setPatient({...patient,diabetes:e.target.value})} placeholder="Optional"/></Field><label className="upload-area"><input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]||null)}/>{preview?<img src={preview} alt="Fundus preview"/>:<><strong>Upload fundus image</strong><span>JPG, JPEG or PNG</span></>}</label>{error&&<p className="form-error">{error}</p>}<div className="screening-actions right"><button className="run-screening-btn" onClick={scan} disabled={busy}>{busy?"Analysing…":"Run screening →"}</button></div></div></div></section></div></main>;
 return <main className="home-page"><div className="page"><nav className="home-nav"><button className="logo">RETO</button><button className="login-btn" onClick={()=>setPage(user?"screening":"login")}>{user?"Open dashboard":"Log in"}</button></nav><section className="hero-section"><div className="hero-content"><p className="hero-eyebrow">RETINAL SCREENING</p><h1>Diabetic retinopathy<span>screening, made clearer.</span></h1><p className="hero-description">AI-assisted retinal screening with secure clinician access, patient history, reports and referral support.</p><div className="hero-buttons"><button className="primary-btn" onClick={()=>setPage(user?"screening":"login")}>Start screening <span>→</span></button></div></div><div className="retina-card"><div className="retina-photo-frame"><img src={fundImage} alt="Retinal fundus image" className="retina-photo"/></div></div></section></div></main>;
}
function Field({label,children}){return <div className="form-group"><label>{label}</label>{children}</div>} function Shell({nav,children}){return <main className="screening-page"><div className="screening-wrapper">{nav}<section className="dashboard">{children}</section></div></main>}
